name: (Multi Arch) Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - docker-hub-deploy

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: akhilrana
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 --push -t akhilrana/telegramarr:multi-arch .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
