name: Publish Docker Image to Docker Hub (ARM64)

on:
  workflow_dispatch:  # Triggered manually

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: akhilrana
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ARM64 Docker image
        run: |
          docker build -t akhilrana/telegramarr:latest-arm64 .
          docker push akhilrana/telegramarr:latest-arm64
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
